### PR TITLE
Add Python documentation

### PR DESCRIPTION
**Pull request by neroist**

### CODE REVIEW

**Comment by neroist** [comment]
Currently, only the file handler documentation is missing. Is this wrapped yet, in webui-python?

**Comment by neroist** [comment]
Should the `myWindow` variable used throughout be changed to snake-case (`myWindow` -> `my_window`)?

**Comment by neroist** [comment]
Let me make additional changes, I intend to make the variable names snake cased

**Comment by neroist** [comment]
Ready to be merged now 👍🏾

**Comment by neroist** [comment]
hm, odd

**Comment by neroist** [comment]
@jinzhongjia can you try approving this pr?

**Review by jinzhongjia — APPROVED** [review]

**Pull request merged**
