### PR TITLE
Fix grammar issues (and such)

### PR DESCRIPTION
**Pull request by neroist**
Fix grammar issues, such as using "support" instead of "supports."

Making this a PR to view changes and make additional ones if necessary.

### CODE REVIEW

**Comment by neroist** [comment]
> Think of WebUI like a WebView controller, but instead of embedding the WebView controller in your program, which makes it big and non-portable, as it needs the WebView runtimes. Instead, using WebUI, you use a tiny static/dynamic library to run any installed web browser and use it as GUI, making your program small, fast, and portable.

These should *not* be two separate sentences. Maybe a semicolon or conjunction could do?

**Comment by neroist** [comment]
Perhaps the ellipses could be replaced with "etc." or just a period? Referring to how they're used in sentences such as these:

> WebUI supports many popular programming languages, such as C/C++, Python, Go, Rust, JavaScript, TypeScript, and more...

> WebUI supports many different web browsers, such as Chrome, Firefox, Edge, Safari, and more...

**Comment by AlbertShown** [comment]
LGTM.

**Comment by AlbertShown** [comment]
Thank you 👍

**Pull request merged**
