### PR TITLE
Update hero image

### PR DESCRIPTION
**Pull request by ttytm**
This updates the hero image to represent the new minimal example. 

Current:
Screenshot_20230907_155814

Proposed:
Screenshot_20230907_163848

The new screenshot has additional line-breaks. I usually wouldn't add them to regular code. But with the new required html it's a bit easier to not lose overview, so I thought it's good it terms of this example screenshot.

Border and shadow styles are now added via CSS. 

<em>Note: The second screenshot shows a change in nav color items that is not included here.</em>

### CODE REVIEW

**Comment by hassandraga** [comment]
Thank you for the update. As you said, the new screenshot has the brake line and no shadow. I prefer to keep the old one. It can be a partial working example but should represent the website.

**Comment by ttytm** [comment]
The new has shadows, just subtler! 
The old has the that you learn not to do at design class 😅

**Comment by ttytm** [comment]
It a partial working example is good, then I think that's better the to keep the example code as well!

**Comment by ttytm** [comment]
As preview I kept the code in the example. Let me know if this is better. Else, lets keep the old one :+1: .
Screenshot_20230907_172421

**Comment by hassandraga** [comment]
LGTM

**Review by hassandraga — APPROVED** [review]

**Comment by ttytm** [comment]
Thanks! I'll reconstruct that updated screenshot with the simpler text and shadow for the readme screenshot for the text-editor over at the webui repo. Then we have it also there :+1:

**Pull request merged**
